# Generated by Django 2.0.3 on 2018-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('stu_ID', models.IntegerField(max_length=32, verbose_name='学号')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('class_stu', models.CharField(max_length=32, verbose_name='班级')),
                ('seat', models.IntegerField(max_length=32, verbose_name='座位')),
                ('course', models.CharField(max_length=32, verbose_name='课程')),
                ('score', models.CharField(max_length=32, verbose_name='成绩')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
        ),
    ]
