# Generated by Django 2.0.3 on 2018-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='seat',
            field=models.IntegerField(verbose_name='座位'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_ID',
            field=models.IntegerField(verbose_name='学号'),
        ),
    ]
